### ISSUE TITLE
Dual MIT/Apache 2.0 License

### ISSUE THREAD

**Issue by DJMcNab** [fschutt/fastblur#16]
Hi @fschutt, @Shnatsel.

We're going through the process of relicensing resvg under the MIT/Apache 2.0 license - see https://github.com/linebender/resvg/issues/838. We are aware that resvg uses code adapted from this crate, see for example discussion in #14. Because of this, we would like to get your permission to use this code under the Apache 2.0 license. The easiest way to do that would be to relicense this project under the same dual license.

If you agree to that, writing a comment in the form should be sufficient:

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

I can follow up with changes to the repository itself to reflect this if you do so.

It is fairly standard in the Rust ecosystem to not have a copyright notice in the MIT license - see https://github.com/rust-lang/rust/pull/43498.
As a separate but related question, would you be willing to remove the copyright notice from the MIT license in this crate? That would mean that we wouldn't need to reproduce the copyright notice on the resvg side (we would of course still provide attribution back to this source, if we continued vendoring), and would allow contributing changes back here trivially (again, see #14)

Thank you for your consideration, and I hope we can reach an agreeable conclusion here!

**Comment by Shnatsel** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by DJMcNab** [comment]
Thank you for the quick reply!

To clarify, I would need both of you to affirmatively agree to remove the copyright notice in order for it to be removed. As I also say, that is less useful for us than adding the Apache 2.0 license, and if you'd rather keep the copyright notice, we can work with that.

**Comment by Shnatsel** [comment]
I agree to remove the copyright notice.

I'm a contributor, not the author, so I don't have any strong opinions on the license here.

**Comment by fschutt** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

@DJMcNab

**Comment by fschutt** [comment]
I don't really care about the licensing, at least for this repo, I just translated the code from JavaScript. Just for big repos I use MPL-2.0 because there were some concerns about some companies not contributing their patches / improvements back to the source repo (but ofc I still want to allow static linking).

**Comment by fschutt** [comment]
Re-merging the changes from resvg is a good idea, I don't want to need to import the entirety of resvg just to blur some images. If you have a PR, you can send it along. Thanks!

**Comment by DJMcNab** [comment]
Thank you! To clarify, what is your position on the copyright notice (i.e. the line `Copyright (c) 2017 Felix Schütt`)?

I'm happy to keep it if you want to, but it does make things more complicated if we do so. Either way, I'll follow up on Monday.

**Comment by DJMcNab** [comment]
Done in #17. Thanks all!
